-- 0003_seed_tickers.sql — Bảng seed 50+ mã (§4.6 BA2) + ticker_aliases.
-- alias_normalized đã bỏ dấu + lowercase, khớp đúng textutil.Normalize của Go.
-- Idempotent qua ON CONFLICT.

INSERT INTO tickers (symbol, company_name, short_name, exchange, sector, in_vn30) VALUES
    ('VIC', 'Tập đoàn Vingroup – CTCP', 'Vingroup', 'HOSE', 'Bất động sản', true),
    ('VHM', 'CTCP Vinhomes', 'Vinhomes', 'HOSE', 'Bất động sản', true),
    ('VRE', 'CTCP Vincom Retail', 'Vincom Retail', 'HOSE', 'Bất động sản', true),
    ('VCB', 'NH TMCP Ngoại Thương Việt Nam', 'Vietcombank', 'HOSE', 'Ngân hàng', true),
    ('BID', 'NH TMCP Đầu tư và Phát triển Việt Nam', 'BIDV', 'HOSE', 'Ngân hàng', true),
    ('CTG', 'NH TMCP Công Thương Việt Nam', 'VietinBank', 'HOSE', 'Ngân hàng', true),
    ('TCB', 'NH TMCP Kỹ Thương Việt Nam', 'Techcombank', 'HOSE', 'Ngân hàng', true),
    ('MBB', 'NH TMCP Quân Đội', 'MB Bank', 'HOSE', 'Ngân hàng', true),
    ('VPB', 'NH TMCP Việt Nam Thịnh Vượng', 'VPBank', 'HOSE', 'Ngân hàng', true),
    ('ACB', 'NH TMCP Á Châu', 'ACB', 'HOSE', 'Ngân hàng', true),
    ('HDB', 'NH TMCP Phát triển TP.HCM', 'HDBank', 'HOSE', 'Ngân hàng', true),
    ('STB', 'NH TMCP Sài Gòn Thương Tín', 'Sacombank', 'HOSE', 'Ngân hàng', true),
    ('SHB', 'NH TMCP Sài Gòn – Hà Nội', 'SHB', 'HOSE', 'Ngân hàng', true),
    ('VIB', 'NH TMCP Quốc tế Việt Nam', 'VIB', 'HOSE', 'Ngân hàng', true),
    ('TPB', 'NH TMCP Tiên Phong', 'TPBank', 'HOSE', 'Ngân hàng', true),
    ('LPB', 'NH TMCP Lộc Phát Việt Nam', 'LPBank', 'HOSE', 'Ngân hàng', true),
    ('SSB', 'NH TMCP Đông Nam Á', 'SeABank', 'HOSE', 'Ngân hàng', true),
    ('MSB', 'NH TMCP Hàng Hải Việt Nam', 'MSB', 'HOSE', 'Ngân hàng', false),
    ('HPG', 'CTCP Tập đoàn Hòa Phát', 'Hòa Phát', 'HOSE', 'Thép', true),
    ('HSG', 'CTCP Tập đoàn Hoa Sen', 'Hoa Sen', 'HOSE', 'Thép', false),
    ('NKG', 'CTCP Thép Nam Kim', 'Nam Kim', 'HOSE', 'Thép', false),
    ('TIS', 'CTCP Gang thép Thái Nguyên', 'Tisco', 'UPCOM', 'Thép', false),
    ('FPT', 'CTCP FPT', 'FPT', 'HOSE', 'Công nghệ', true),
    ('CMG', 'CTCP Tập đoàn Công nghệ CMC', 'CMC', 'HOSE', 'Công nghệ', false),
    ('MWG', 'CTCP Đầu tư Thế Giới Di Động', 'Thế Giới Di Động', 'HOSE', 'Bán lẻ', true),
    ('MSN', 'CTCP Tập đoàn Masan', 'Masan', 'HOSE', 'Thực phẩm & đồ uống', true),
    ('MML', 'CTCP Masan MEATLife', 'Masan MEATLife', 'UPCOM', 'Chăn nuôi', false),
    ('VNM', 'CTCP Sữa Việt Nam', 'Vinamilk', 'HOSE', 'Thực phẩm & đồ uống', true),
    ('SAB', 'Tổng CTCP Bia – Rượu – NGK Sài Gòn', 'Sabeco', 'HOSE', 'Thực phẩm & đồ uống', true),
    ('GAS', 'Tổng Công ty Khí Việt Nam – CTCP', 'PV GAS', 'HOSE', 'Dầu khí', true),
    ('PLX', 'Tập đoàn Xăng dầu Việt Nam', 'Petrolimex', 'HOSE', 'Dầu khí', true),
    ('PVS', 'Tổng CTCP Dịch vụ Kỹ thuật Dầu khí Việt Nam', 'PTSC', 'HNX', 'Dầu khí', false),
    ('PVD', 'Tổng CTCP Khoan và Dịch vụ Khoan Dầu khí', 'PV Drilling', 'HOSE', 'Dầu khí', false),
    ('POW', 'Tổng Công ty Điện lực Dầu khí Việt Nam – CTCP', 'PV Power', 'HOSE', 'Điện', true),
    ('REE', 'CTCP Cơ Điện Lạnh', 'REE', 'HOSE', 'Điện', false),
    ('GEX', 'CTCP Tập đoàn GELEX', 'GELEX', 'HOSE', 'Công nghiệp', false),
    ('GVR', 'Tập đoàn Công nghiệp Cao su Việt Nam – CTCP', 'Cao su Việt Nam', 'HOSE', 'BĐS khu công nghiệp', true),
    ('BCM', 'Tổng CT Đầu tư và Phát triển Công nghiệp – CTCP', 'Becamex', 'HOSE', 'BĐS khu công nghiệp', true),
    ('KDH', 'CTCP Đầu tư và Kinh doanh Nhà Khang Điền', 'Khang Điền', 'HOSE', 'Bất động sản', false),
    ('DXG', 'CTCP Tập đoàn Đất Xanh', 'Đất Xanh', 'HOSE', 'Bất động sản', false),
    ('NLG', 'CTCP Đầu tư Nam Long', 'Nam Long', 'HOSE', 'Bất động sản', false),
    ('VJC', 'CTCP Hàng không VietJet', 'VietJet', 'HOSE', 'Hàng không', true),
    ('ACV', 'Tổng CT Cảng hàng không Việt Nam – CTCP', 'ACV', 'UPCOM', 'Hàng không', false),
    ('BVH', 'Tập đoàn Bảo Việt', 'Bảo Việt', 'HOSE', 'Bảo hiểm', true),
    ('SSI', 'CTCP Chứng khoán SSI', 'SSI', 'HOSE', 'Dịch vụ tài chính', true),
    ('VND', 'CTCP Chứng khoán VNDIRECT', 'VNDIRECT', 'HOSE', 'Dịch vụ tài chính', false),
    ('VCI', 'CTCP Chứng khoán Vietcap', 'Vietcap', 'HOSE', 'Dịch vụ tài chính', false),
    ('DGC', 'CTCP Tập đoàn Hóa chất Đức Giang', 'Đức Giang', 'HOSE', 'Hóa chất', false),
    ('DBC', 'CTCP Tập đoàn Dabaco Việt Nam', 'Dabaco', 'HOSE', 'Chăn nuôi', false),
    ('BAF', 'CTCP Nông nghiệp BAF Việt Nam', 'BAF', 'HOSE', 'Chăn nuôi', false),
    ('PNJ', 'CTCP Vàng bạc Đá quý Phú Nhuận', 'PNJ', 'HOSE', 'Bán lẻ', false),
    ('HAG', 'CTCP Hoàng Anh Gia Lai', 'Hoàng Anh Gia Lai', 'HOSE', 'Chăn nuôi', false),
    ('NAB', 'NH TMCP Nam Á', 'Nam A Bank', 'HOSE', 'Ngân hàng', false),
    ('NVB', 'NH TMCP Quốc Dân', 'NCB', 'HNX', 'Ngân hàng', false),
    ('SGB', 'NH TMCP Sài Gòn Công Thương', 'Saigonbank', 'UPCOM', 'Ngân hàng', false),
    ('BVB', 'NH TMCP Bản Việt', 'BVBank', 'UPCOM', 'Ngân hàng', false)
ON CONFLICT (symbol) DO UPDATE SET
    company_name = EXCLUDED.company_name,
    short_name   = EXCLUDED.short_name,
    exchange     = EXCLUDED.exchange,
    sector       = EXCLUDED.sector,
    in_vn30      = EXCLUDED.in_vn30;

INSERT INTO ticker_aliases (symbol, alias, alias_normalized) VALUES
    ('VIC', 'Tập đoàn Vingroup – CTCP', 'tap doan vingroup ctcp'),
    ('VIC', 'Vingroup', 'vingroup'),
    ('VIC', 'Tập đoàn Vingroup', 'tap doan vingroup'),
    ('VHM', 'CTCP Vinhomes', 'ctcp vinhomes'),
    ('VHM', 'Vinhomes', 'vinhomes'),
    ('VRE', 'CTCP Vincom Retail', 'ctcp vincom retail'),
    ('VRE', 'Vincom Retail', 'vincom retail'),
    ('VCB', 'NH TMCP Ngoại Thương Việt Nam', 'nh tmcp ngoai thuong viet nam'),
    ('VCB', 'Vietcombank', 'vietcombank'),
    ('VCB', 'Ngân hàng Ngoại Thương', 'ngan hang ngoai thuong'),
    ('VCB', 'NH Ngoại Thương', 'nh ngoai thuong'),
    ('BID', 'NH TMCP Đầu tư và Phát triển Việt Nam', 'nh tmcp dau tu va phat trien viet nam'),
    ('BID', 'BIDV', 'bidv'),
    ('BID', 'Ngân hàng Đầu tư và Phát triển', 'ngan hang dau tu va phat trien'),
    ('CTG', 'NH TMCP Công Thương Việt Nam', 'nh tmcp cong thuong viet nam'),
    ('CTG', 'VietinBank', 'vietinbank'),
    ('CTG', 'Ngân hàng Công Thương', 'ngan hang cong thuong'),
    ('TCB', 'NH TMCP Kỹ Thương Việt Nam', 'nh tmcp ky thuong viet nam'),
    ('TCB', 'Techcombank', 'techcombank'),
    ('TCB', 'Ngân hàng Kỹ Thương', 'ngan hang ky thuong'),
    ('MBB', 'NH TMCP Quân Đội', 'nh tmcp quan doi'),
    ('MBB', 'MB Bank', 'mb bank'),
    ('MBB', 'MBBank', 'mbbank'),
    ('MBB', 'Ngân hàng Quân Đội', 'ngan hang quan doi'),
    ('VPB', 'NH TMCP Việt Nam Thịnh Vượng', 'nh tmcp viet nam thinh vuong'),
    ('VPB', 'VPBank', 'vpbank'),
    ('VPB', 'Ngân hàng Việt Nam Thịnh Vượng', 'ngan hang viet nam thinh vuong'),
    ('ACB', 'NH TMCP Á Châu', 'nh tmcp a chau'),
    ('ACB', 'Ngân hàng Á Châu', 'ngan hang a chau'),
    ('HDB', 'NH TMCP Phát triển TP.HCM', 'nh tmcp phat trien tp hcm'),
    ('HDB', 'HDBank', 'hdbank'),
    ('HDB', 'HD Bank', 'hd bank'),
    ('STB', 'NH TMCP Sài Gòn Thương Tín', 'nh tmcp sai gon thuong tin'),
    ('STB', 'Sacombank', 'sacombank'),
    ('STB', 'Ngân hàng Sài Gòn Thương Tín', 'ngan hang sai gon thuong tin'),
    ('SHB', 'NH TMCP Sài Gòn – Hà Nội', 'nh tmcp sai gon ha noi'),
    ('SHB', 'Ngân hàng Sài Gòn Hà Nội', 'ngan hang sai gon ha noi'),
    ('VIB', 'NH TMCP Quốc tế Việt Nam', 'nh tmcp quoc te viet nam'),
    ('VIB', 'Ngân hàng Quốc tế Việt Nam', 'ngan hang quoc te viet nam'),
    ('TPB', 'NH TMCP Tiên Phong', 'nh tmcp tien phong'),
    ('TPB', 'TPBank', 'tpbank'),
    ('TPB', 'Ngân hàng Tiên Phong', 'ngan hang tien phong'),
    ('LPB', 'NH TMCP Lộc Phát Việt Nam', 'nh tmcp loc phat viet nam'),
    ('LPB', 'LPBank', 'lpbank'),
    ('LPB', 'Lộc Phát', 'loc phat'),
    ('LPB', 'LienVietPostBank', 'lienvietpostbank'),
    ('SSB', 'NH TMCP Đông Nam Á', 'nh tmcp dong nam a'),
    ('SSB', 'SeABank', 'seabank'),
    ('SSB', 'Ngân hàng Đông Nam Á', 'ngan hang dong nam a'),
    ('MSB', 'NH TMCP Hàng Hải Việt Nam', 'nh tmcp hang hai viet nam'),
    ('MSB', 'Maritime Bank', 'maritime bank'),
    ('MSB', 'Ngân hàng Hàng Hải', 'ngan hang hang hai'),
    ('HPG', 'CTCP Tập đoàn Hòa Phát', 'ctcp tap doan hoa phat'),
    ('HPG', 'Hòa Phát', 'hoa phat'),
    ('HPG', 'Tập đoàn Hòa Phát', 'tap doan hoa phat'),
    ('HSG', 'CTCP Tập đoàn Hoa Sen', 'ctcp tap doan hoa sen'),
    ('HSG', 'Hoa Sen', 'hoa sen'),
    ('HSG', 'Tôn Hoa Sen', 'ton hoa sen'),
    ('HSG', 'Tập đoàn Hoa Sen', 'tap doan hoa sen'),
    ('NKG', 'CTCP Thép Nam Kim', 'ctcp thep nam kim'),
    ('NKG', 'Nam Kim', 'nam kim'),
    ('NKG', 'Thép Nam Kim', 'thep nam kim'),
    ('TIS', 'CTCP Gang thép Thái Nguyên', 'ctcp gang thep thai nguyen'),
    ('TIS', 'Tisco', 'tisco'),
    ('TIS', 'Gang thép Thái Nguyên', 'gang thep thai nguyen'),
    ('FPT', 'CTCP FPT', 'ctcp fpt'),
    ('FPT', 'Tập đoàn FPT', 'tap doan fpt'),
    ('CMG', 'CTCP Tập đoàn Công nghệ CMC', 'ctcp tap doan cong nghe cmc'),
    ('CMG', 'CMC', 'cmc'),
    ('CMG', 'Tập đoàn CMC', 'tap doan cmc'),
    ('CMG', 'CMC Telecom', 'cmc telecom'),
    ('CMG', 'CMC Cloud', 'cmc cloud'),
    ('CMG', 'Tập đoàn Công nghệ CMC', 'tap doan cong nghe cmc'),
    ('MWG', 'CTCP Đầu tư Thế Giới Di Động', 'ctcp dau tu the gioi di dong'),
    ('MWG', 'Thế Giới Di Động', 'the gioi di dong'),
    ('MWG', 'TGDĐ', 'tgdd'),
    ('MWG', 'Bách Hoá Xanh', 'bach hoa xanh'),
    ('MWG', 'Điện Máy Xanh', 'dien may xanh'),
    ('MSN', 'CTCP Tập đoàn Masan', 'ctcp tap doan masan'),
    ('MSN', 'Masan', 'masan'),
    ('MSN', 'Tập đoàn Masan', 'tap doan masan'),
    ('MSN', 'WinMart', 'winmart'),
    ('MSN', 'WinCommerce', 'wincommerce'),
    ('MML', 'CTCP Masan MEATLife', 'ctcp masan meatlife'),
    ('MML', 'Masan MEATLife', 'masan meatlife'),
    ('MML', 'MEATDeli', 'meatdeli'),
    ('VNM', 'CTCP Sữa Việt Nam', 'ctcp sua viet nam'),
    ('VNM', 'Vinamilk', 'vinamilk'),
    ('VNM', 'Sữa Việt Nam', 'sua viet nam'),
    ('SAB', 'Tổng CTCP Bia – Rượu – NGK Sài Gòn', 'tong ctcp bia ruou ngk sai gon'),
    ('SAB', 'Sabeco', 'sabeco'),
    ('SAB', 'Bia Sài Gòn', 'bia sai gon'),
    ('GAS', 'Tổng Công ty Khí Việt Nam – CTCP', 'tong cong ty khi viet nam ctcp'),
    ('GAS', 'PV GAS', 'pv gas'),
    ('GAS', 'PVGas', 'pvgas'),
    ('GAS', 'Khí Việt Nam', 'khi viet nam'),
    ('PLX', 'Tập đoàn Xăng dầu Việt Nam', 'tap doan xang dau viet nam'),
    ('PLX', 'Petrolimex', 'petrolimex'),
    ('PLX', 'Tập đoàn Xăng dầu', 'tap doan xang dau'),
    ('PVS', 'Tổng CTCP Dịch vụ Kỹ thuật Dầu khí Việt Nam', 'tong ctcp dich vu ky thuat dau khi viet nam'),
    ('PVS', 'PTSC', 'ptsc'),
    ('PVS', 'Dịch vụ Kỹ thuật Dầu khí', 'dich vu ky thuat dau khi'),
    ('PVD', 'Tổng CTCP Khoan và Dịch vụ Khoan Dầu khí', 'tong ctcp khoan va dich vu khoan dau khi'),
    ('PVD', 'PV Drilling', 'pv drilling'),
    ('PVD', 'Khoan Dầu khí', 'khoan dau khi'),
    ('POW', 'Tổng Công ty Điện lực Dầu khí Việt Nam – CTCP', 'tong cong ty dien luc dau khi viet nam ctcp'),
    ('POW', 'PV Power', 'pv power'),
    ('POW', 'Điện lực Dầu khí', 'dien luc dau khi'),
    ('REE', 'CTCP Cơ Điện Lạnh', 'ctcp co dien lanh'),
    ('REE', 'Cơ Điện Lạnh', 'co dien lanh'),
    ('GEX', 'CTCP Tập đoàn GELEX', 'ctcp tap doan gelex'),
    ('GEX', 'GELEX', 'gelex'),
    ('GEX', 'Tập đoàn GELEX', 'tap doan gelex'),
    ('GVR', 'Tập đoàn Công nghiệp Cao su Việt Nam – CTCP', 'tap doan cong nghiep cao su viet nam ctcp'),
    ('GVR', 'Cao su Việt Nam', 'cao su viet nam'),
    ('GVR', 'VRG', 'vrg'),
    ('BCM', 'Tổng CT Đầu tư và Phát triển Công nghiệp – CTCP', 'tong ct dau tu va phat trien cong nghiep ctcp'),
    ('BCM', 'Becamex', 'becamex'),
    ('BCM', 'Becamex IDC', 'becamex idc'),
    ('KDH', 'CTCP Đầu tư và Kinh doanh Nhà Khang Điền', 'ctcp dau tu va kinh doanh nha khang dien'),
    ('KDH', 'Khang Điền', 'khang dien'),
    ('KDH', 'Nhà Khang Điền', 'nha khang dien'),
    ('DXG', 'CTCP Tập đoàn Đất Xanh', 'ctcp tap doan dat xanh'),
    ('DXG', 'Đất Xanh', 'dat xanh'),
    ('DXG', 'Tập đoàn Đất Xanh', 'tap doan dat xanh'),
    ('NLG', 'CTCP Đầu tư Nam Long', 'ctcp dau tu nam long'),
    ('NLG', 'Nam Long', 'nam long'),
    ('NLG', 'Đầu tư Nam Long', 'dau tu nam long'),
    ('VJC', 'CTCP Hàng không VietJet', 'ctcp hang khong vietjet'),
    ('VJC', 'VietJet', 'vietjet'),
    ('VJC', 'Vietjet Air', 'vietjet air'),
    ('ACV', 'Tổng CT Cảng hàng không Việt Nam – CTCP', 'tong ct cang hang khong viet nam ctcp'),
    ('ACV', 'Cảng hàng không Việt Nam', 'cang hang khong viet nam'),
    ('BVH', 'Tập đoàn Bảo Việt', 'tap doan bao viet'),
    ('BVH', 'Bảo Việt', 'bao viet'),
    ('VND', 'VNDIRECT', 'vndirect'),
    ('VCI', 'Vietcap', 'vietcap'),
    ('VCI', 'VCSC', 'vcsc'),
    ('DGC', 'CTCP Tập đoàn Hóa chất Đức Giang', 'ctcp tap doan hoa chat duc giang'),
    ('DGC', 'Đức Giang', 'duc giang'),
    ('DGC', 'Hóa chất Đức Giang', 'hoa chat duc giang'),
    ('DBC', 'CTCP Tập đoàn Dabaco Việt Nam', 'ctcp tap doan dabaco viet nam'),
    ('DBC', 'Dabaco', 'dabaco'),
    ('DBC', 'Tập đoàn Dabaco', 'tap doan dabaco'),
    ('BAF', 'CTCP Nông nghiệp BAF Việt Nam', 'ctcp nong nghiep baf viet nam'),
    ('BAF', 'Nông nghiệp BAF', 'nong nghiep baf'),
    ('BAF', 'BAF Meat', 'baf meat'),
    ('PNJ', 'CTCP Vàng bạc Đá quý Phú Nhuận', 'ctcp vang bac da quy phu nhuan'),
    ('PNJ', 'Vàng bạc Đá quý Phú Nhuận', 'vang bac da quy phu nhuan'),
    ('HAG', 'CTCP Hoàng Anh Gia Lai', 'ctcp hoang anh gia lai'),
    ('HAG', 'Hoàng Anh Gia Lai', 'hoang anh gia lai'),
    ('HAG', 'HAGL', 'hagl'),
    ('NAB', 'NH TMCP Nam Á', 'nh tmcp nam a'),
    ('NAB', 'Nam A Bank', 'nam a bank'),
    ('NAB', 'Ngân hàng Nam Á', 'ngan hang nam a'),
    ('NVB', 'NH TMCP Quốc Dân', 'nh tmcp quoc dan'),
    ('NVB', 'NCB', 'ncb'),
    ('NVB', 'Ngân hàng Quốc Dân', 'ngan hang quoc dan'),
    ('SGB', 'NH TMCP Sài Gòn Công Thương', 'nh tmcp sai gon cong thuong'),
    ('SGB', 'Saigonbank', 'saigonbank'),
    ('SGB', 'Ngân hàng Sài Gòn Công Thương', 'ngan hang sai gon cong thuong'),
    ('BVB', 'NH TMCP Bản Việt', 'nh tmcp ban viet'),
    ('BVB', 'BVBank', 'bvbank'),
    ('BVB', 'Ngân hàng Bản Việt', 'ngan hang ban viet')
ON CONFLICT (symbol, alias_normalized) DO NOTHING;
